# Generated by Django 3.2.2 on 2021-05-09 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='date of create')),
                ('creator', models.CharField(max_length=100, verbose_name='creator')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('title', models.CharField(max_length=100, verbose_name='عنوان پست')),
            ],
        ),
    ]
