# Generated by Django 3.2.2 on 2021-05-16 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('selecao', '0002_auto_20210515_0633'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='created date')),
                ('content', models.TextField(null=True, verbose_name='content')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('intro_image', models.ImageField(blank=True, null=True, upload_to='', verbose_name='intro image')),
                ('show_post', models.BooleanField(verbose_name='show post')),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='creator')),
            ],
            options={
                'verbose_name': 'پست',
                'verbose_name_plural': 'پست ها',
                'ordering': ('title',),
            },
        ),
    ]
