# Generated by Django 3.2.2 on 2021-05-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selecao', '0003_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('title',), 'verbose_name': 'post', 'verbose_name_plural': 'posts'},
        ),
    ]
